<?php
if (!defined('IN_SIMPLECMS')) { die('Прямой доступ запрещен');}
return array (
  'host' => 'localhost',
  'database' => 'u2339566_default',
  'db_user' => 'u2339566_default',
  'db_pass' => '7zE7CZq6tZn4RDAj',
  'home_title' => 'Заголовок вашего сайта',
  'templ' => 'simple',
  'db_prefix' => 'release_',
  'csrf_token_name' => 'csrf_token',
  'max_backups' => 5,
  'backup_schedule' => 'weekly',
  'backup_dir' => 'admin/backups/',
  'blocks_for_reg' => true,
  'metaKeywords' => 'Здесь ключевые слова, через запятую (,)',
  'metaDescription' => 'Здесь описание вашего сайта',
  'mail_from' => 'no-reply@release.yunisov.tech',
  'mail_from_name' => 'SimpleBlog Notifications',
  'blogs_per_page' => '6',
  'comments_per_page' => '3',
  'powered' => 'simpleBlog',
  'version' => 'v0.8.0',
  'debug' => true,
  'update_check_interval' => 86400,
  'disable_update_check' => false,
  'github_repo' => 'pumba250/simpleBlog',
  'install_ip' => '84.47.170.190',
  'install_time' => 1751207424,
  'cache_enabled' => '',
  'cache_driver' => 'file',
  'cache_ttl' => '600',
  'cache_key_salt' => 'release.yunisov.tech',
  'redis_host' => '127.0.0.1',
  'redis_port' => '6379',
  'memcached_host' => '127.0.0.1',
  'memcached_port' => '11211',
);
