name: Load Test - Don't Merge If Slow

on:
  pull_request:
    branches: [ main ]

jobs:
  load-test-k6:
    runs-on: ubuntu-latest
    steps:
      name: Забираем код
      uses: actions/checkout@v4

      name: Ставим k6
      uses: grafana/setup-k6@v1

      name: Гоняем нагрузку как надо
      run: |
          k6 run --threshold "http_req_duration{p(95)<800}" src/loadtest.js
      env:
         BASE_URL: ${{ secrets.TEST_ENV }}

      name: Если упало — светимся красным
        if: failure()
        run: |
          echo "ВСЁ ПРОПАЛО. ПАЙПЛАЙН УПАЛ. МЕРЖИТЬ НЕЛЬЗЯ."
