name: Deploy to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      pages_enabled: ${{ steps.check-pages.outputs.enabled }}
    steps:
      - name: Check if GitHub Pages is enabled
        id: check-pages
        run: |
          # Простая проверка - если папка _site существует, считаем что Pages активен
          if [ -d "_site" ]; then
            echo "enabled=true" >> $GITHUB_OUTPUT
          else
            echo "enabled=false" >> $GITHUB_OUTPUT
          fi

  build:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.pages_enabled == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create simple page
        run: |
          mkdir -p _site
          echo "<h1>SimpleBlogCMS</h1><p>Working!</p>" > _site/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3

  error:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.pages_enabled == 'false'
    steps:
      - name: Show error message
        run: |
          echo "❌ ERROR: GitHub Pages not enabled!"
          echo "Please go to: https://github.com/pumba250/simpleBlogCMS/settings/pages"
          echo "Select 'GitHub Actions' as source and click Save"
          echo ""
          echo "If the option is not available, your repository might be:"
          echo "- Private (upgrade to GitHub Pro or make public)"
          echo "- Not have GitHub Pages enabled by organization settings"
          exit 1
